import json
from atlasmind.core.planning.refiner.schema import PlanRefinementSchema


# -------------------------------------------------------------------
# Base LLM prompt template
# -------------------------------------------------------------------
BASE_PLAN_PROMPT = """
You are an intelligent planning assistant responsible for refining structured reasoning plans.
You will receive a user question and a base execution plan generated by a classification model.

Your goals are to:
1. Understand the question to identify entities, intent, and relevant context.
2. Specialize the plan steps to make them specific to the question.
3. Extract structured metadata describing what the question is about and what kind of output is expected.

--- INPUTS ---
User question:
"{question}"

Base plan steps:
{plan_steps}

--- OUTPUT FORMAT ---
Respond ONLY in **valid JSON** matching this schema:
{schema_json}

--- INSTRUCTIONS ---
- Maintain the same logical step order.
- Replace generic text with context-specific details (entities, years, filters, etc.).
- Do NOT include commentary or explanations outside JSON.
- Keep JSON minimal and valid.
- Confidence should be a number between 0.0 and 1.0.
- If any field is unknown, return it as null or empty.
"""

# -------------------------------------------------------------------
# Context hints per tool / reasoning type
# -------------------------------------------------------------------
CONTEXT_HINTS = {
    "WikipediaTool": "This task involves factual or entity-based retrieval from Wikipedia articles.",
    "WebSearchTool": "This task involves open-domain search. Focus on keyword and query intent extraction.",
    "AudioTranscriberTool": "This involves audio input. Focus on transcription and meaning extraction.",
    "VideoTranscriptTool": "This involves video input. Focus on transcript and scene summarization.",
    "ImageAnalyzerTool": "This involves image input. Focus on detected objects, visual elements, and descriptions.",
    "ExcelTool": "This involves structured data (spreadsheets). Identify sheets, columns, and numeric fields.",
    "CodeRunnerTool": "This involves code. Detect the programming language and execution purpose.",
    "SemanticTool": "This involves meaning and relationships. Identify entities and their semantic categories.",
    "TextClassifierTool": "This involves text analysis. Focus on classification, tone, or logic reasoning.",
}


# -------------------------------------------------------------------
# Prompt builder
# -------------------------------------------------------------------
def build_plan_prompt(question: str, plan_steps: list, tool_name: str) -> str:
    """Builds a complete contextualized prompt for the LLM plan refinement step."""
    schema_json = json.dumps(PlanRefinementSchema.SCHEMA_EXAMPLE, indent=2, ensure_ascii=False)
    base_prompt = BASE_PLAN_PROMPT.format(
        question=question,
        plan_steps=json.dumps(plan_steps, indent=2, ensure_ascii=False),
        schema_json=schema_json
    )

    context_hint = CONTEXT_HINTS.get(tool_name, "")
    if context_hint:
        base_prompt += f"\n\n--- CONTEXT HINT ---\n{context_hint}"

    return base_prompt
